/**
 * @biref uDMA register defs
 */

#pragma once

#include "registers/register_helpers.h"

// uDMA Register Offsets
#define  UDMA_STAT_OFFSET         0x00000000
#define  UDMA_CFG_OFFSET          0x00000004
#define  UDMA_CTLBASE_OFFSET      0x00000008
#define  UDMA_ALTBASE_OFFSET      0x0000000C
#define  UDMA_WAITSTAT_OFFSET     0x00000010
#define  UDMA_SWREQ_OFFSET        0x00000014
#define  UDMA_USEBURSTSET_OFFSET  0x00000018
#define  UDMA_USEBURSTCLR_OFFSET  0x0000001C
#define  UDMA_REQMASKSET_OFFSET   0x00000020
#define  UDMA_REQMASKCLR_OFFSET   0x00000024
#define  UDMA_ENASET_OFFSET       0x00000028
#define  UDMA_ENACLR_OFFSET       0x0000002C
#define  UDMA_ALTSET_OFFSET       0x00000030
#define  UDMA_ALTCLR_OFFSET       0x00000034
#define  UDMA_PRIOSET_OFFSET      0x00000038
#define  UDMA_PRIOCLR_OFFSET      0x0000003C
#define  UDMA_ERRCLR_OFFSET       0x0000004C
#define  UDMA_CHASGN_OFFSET       0x00000500
#define  UDMA_CHMAP0_OFFSET       0x00000510
#define  UDMA_CHMAP1_OFFSET       0x00000514
#define  UDMA_CHMAP2_OFFSET       0x00000518
#define  UDMA_CHMAP3_OFFSET       0x0000051C
#define  UDMA_PeriphID4_OFFSET    0x00000FD0
#define  UDMA_PeriphID0_OFFSET    0x00000FE0
#define  UDMA_PeriphID1_OFFSET    0x00000FE4
#define  UDMA_PeriphID2_OFFSET    0x00000FE8
#define  UDMA_PeriphID3_OFFSET    0x00000FEC
#define  UDMA_PCellID0_OFFSET     0x00000FF0
#define  UDMA_PCellID1_OFFSET     0x00000FF4
#define  UDMA_PCellID2_OFFSET     0x00000FF8
#define  UDMA_PCellID3_OFFSET     0x00000FFC

// uDMA Base Address
#define UDMA_BASE 0x400FF000

// uDMA Register Definitions
#define  UDMA_STAT         REGISTER(UDMA_BASE + UDMA_STAT_OFFSET)
#define  UDMA_CFG          REGISTER(UDMA_BASE + UDMA_CFG_OFFSET)
#define  UDMA_CTLBASE      REGISTER(UDMA_BASE + UDMA_CTLBASE_OFFSET)
#define  UDMA_ALTBASE      REGISTER(UDMA_BASE + UDMA_ALTBASE_OFFSET)
#define  UDMA_WAITSTAT     REGISTER(UDMA_BASE + UDMA_WAITSTAT_OFFSET)
#define  UDMA_SWREQ        REGISTER(UDMA_BASE + UDMA_SWREQ_OFFSET)
#define  UDMA_USEBURSTSET  REGISTER(UDMA_BASE + UDMA_USEBURSTSET_OFFSET)
#define  UDMA_USEBURSTCLR  REGISTER(UDMA_BASE + UDMA_USEBURSTCLR_OFFSET)
#define  UDMA_REQMASKSET   REGISTER(UDMA_BASE + UDMA_REQMASKSET_OFFSET)
#define  UDMA_REQMASKCLR   REGISTER(UDMA_BASE + UDMA_REQMASKCLR_OFFSET)
#define  UDMA_ENASET       REGISTER(UDMA_BASE + UDMA_ENASET_OFFSET)
#define  UDMA_ENACLR       REGISTER(UDMA_BASE + UDMA_ENACLR_OFFSET)
#define  UDMA_ALTSET       REGISTER(UDMA_BASE + UDMA_ALTSET_OFFSET)
#define  UDMA_ALTCLR       REGISTER(UDMA_BASE + UDMA_ALTCLR_OFFSET)
#define  UDMA_PRIOSET      REGISTER(UDMA_BASE + UDMA_PRIOSET_OFFSET)
#define  UDMA_PRIOCLR      REGISTER(UDMA_BASE + UDMA_PRIOCLR_OFFSET)
#define  UDMA_ERRCLR       REGISTER(UDMA_BASE + UDMA_ERRCLR_OFFSET)
#define  UDMA_CHASGN       REGISTER(UDMA_BASE + UDMA_CHASGN_OFFSET)
#define  UDMA_CHMAP0       REGISTER(UDMA_BASE + UDMA_CHMAP0_OFFSET)
#define  UDMA_CHMAP1       REGISTER(UDMA_BASE + UDMA_CHMAP1_OFFSET)
#define  UDMA_CHMAP2       REGISTER(UDMA_BASE + UDMA_CHMAP2_OFFSET)
#define  UDMA_CHMAP3       REGISTER(UDMA_BASE + UDMA_CHMAP3_OFFSET)
#define  UDMA_PeriphID4    REGISTER(UDMA_BASE + UDMA_PeriphID4_OFFSET)
#define  UDMA_PeriphID0    REGISTER(UDMA_BASE + UDMA_PeriphID0_OFFSET)
#define  UDMA_PeriphID1    REGISTER(UDMA_BASE + UDMA_PeriphID1_OFFSET)
#define  UDMA_PeriphID2    REGISTER(UDMA_BASE + UDMA_PeriphID2_OFFSET)
#define  UDMA_PeriphID3    REGISTER(UDMA_BASE + UDMA_PeriphID3_OFFSET)
#define  UDMA_PCellID0     REGISTER(UDMA_BASE + UDMA_PCellID0_OFFSET)
#define  UDMA_PCellID1     REGISTER(UDMA_BASE + UDMA_PCellID1_OFFSET)
#define  UDMA_PCellID2     REGISTER(UDMA_BASE + UDMA_PCellID2_OFFSET)
#define  UDMA_PCellID3     REGISTER(UDMA_BASE + UDMA_PCellID3_OFFSET)
